baseURL = "https://chenzhuoji.github.io/"
title = "Chenzhuo's Blog"
theme = "PaperMod"
languageCode = "zh-cn"

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showToc = true
  tocOpen = false

[outputs]
  home = ["HTML", "RSS", "JSON"]


